version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgresContainer
    volumes:
      - ./databases:/var/lib/postgres
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  backend:
    image: ingresso_backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - db_user=${POSTGRES_USER}
      - db_name=${POSTGRES_DB}
      - db_password=${POSTGRES_PASSWORD}
    depends_on:
      - db

  frontend:
    image: ingresso_frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend